# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nathan/src/osgearth

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nathan/src/osgearth

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	cd /home/nathan/src/osgearth && /usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	cd /home/nathan/src/osgearth && /usr/bin/cpack --config ./CPackSourceConfig.cmake /home/nathan/src/osgearth/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/nathan/src/osgearth && $(CMAKE_COMMAND) -E cmake_progress_start /home/nathan/src/osgearth/CMakeFiles /home/nathan/src/osgearth/src/applications/3DTerrain/CMakeFiles/progress.marks
	cd /home/nathan/src/osgearth && $(MAKE) -f CMakeFiles/Makefile2 src/applications/3DTerrain/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nathan/src/osgearth/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/nathan/src/osgearth && $(MAKE) -f CMakeFiles/Makefile2 src/applications/3DTerrain/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/nathan/src/osgearth && $(MAKE) -f CMakeFiles/Makefile2 src/applications/3DTerrain/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/nathan/src/osgearth && $(MAKE) -f CMakeFiles/Makefile2 src/applications/3DTerrain/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/nathan/src/osgearth && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/rule:
	cd /home/nathan/src/osgearth && $(MAKE) -f CMakeFiles/Makefile2 src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/rule
.PHONY : src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/rule

# Convenience name for target.
application_3DTerrain: src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/rule
.PHONY : application_3DTerrain

# fast build rule for target.
application_3DTerrain/fast:
	cd /home/nathan/src/osgearth && $(MAKE) -f src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/build.make src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/build
.PHONY : application_3DTerrain/fast

3DTerrain.o: 3DTerrain.cpp.o
.PHONY : 3DTerrain.o

# target to build an object file
3DTerrain.cpp.o:
	cd /home/nathan/src/osgearth && $(MAKE) -f src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/build.make src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/3DTerrain.cpp.o
.PHONY : 3DTerrain.cpp.o

3DTerrain.i: 3DTerrain.cpp.i
.PHONY : 3DTerrain.i

# target to preprocess a source file
3DTerrain.cpp.i:
	cd /home/nathan/src/osgearth && $(MAKE) -f src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/build.make src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/3DTerrain.cpp.i
.PHONY : 3DTerrain.cpp.i

3DTerrain.s: 3DTerrain.cpp.s
.PHONY : 3DTerrain.s

# target to generate assembly for a file
3DTerrain.cpp.s:
	cd /home/nathan/src/osgearth && $(MAKE) -f src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/build.make src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/3DTerrain.cpp.s
.PHONY : 3DTerrain.cpp.s

SDLIntegration.o: SDLIntegration.cpp.o
.PHONY : SDLIntegration.o

# target to build an object file
SDLIntegration.cpp.o:
	cd /home/nathan/src/osgearth && $(MAKE) -f src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/build.make src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/SDLIntegration.cpp.o
.PHONY : SDLIntegration.cpp.o

SDLIntegration.i: SDLIntegration.cpp.i
.PHONY : SDLIntegration.i

# target to preprocess a source file
SDLIntegration.cpp.i:
	cd /home/nathan/src/osgearth && $(MAKE) -f src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/build.make src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/SDLIntegration.cpp.i
.PHONY : SDLIntegration.cpp.i

SDLIntegration.s: SDLIntegration.cpp.s
.PHONY : SDLIntegration.s

# target to generate assembly for a file
SDLIntegration.cpp.s:
	cd /home/nathan/src/osgearth && $(MAKE) -f src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/build.make src/applications/3DTerrain/CMakeFiles/application_3DTerrain.dir/SDLIntegration.cpp.s
.PHONY : SDLIntegration.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... application_3DTerrain"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... 3DTerrain.o"
	@echo "... 3DTerrain.i"
	@echo "... 3DTerrain.s"
	@echo "... SDLIntegration.o"
	@echo "... SDLIntegration.i"
	@echo "... SDLIntegration.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/nathan/src/osgearth && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

